// Generates public/curl/config.sh from data/site.ts + data/socials.ts so the
// bash card and the site can never drift. Runs before dev/build/test (see
// package.json scripts). Relative imports on purpose — this runs under tsx
// outside Next's resolver.
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { site } from "../data/site";
import { socials } from "../data/socials";

// config.sh is sourced by bash inside the request path on Vercel. Emit every
// data value single-quoted ('\'' idiom) — inside POSIX single quotes nothing
// else is special. Never switch this to double quotes.
const sq = (value: string): string => {
  if (/[\x00-\x1f\x7f]/.test(value)) {
    throw new Error(`Control character in config value: ${JSON.stringify(value)}`);
  }
  return `'${value.replace(/'/g, `'\\''`)}'`;
};

const byIcon = (icon: string) => {
  const social = socials.find((s) => s.icon === icon);
  if (!social) throw new Error(`No social with icon "${icon}"`);
  return social;
};

const config = `#!/usr/bin/env bash
# GENERATED by scripts/generate-curl-config.ts — do not edit by hand.
# Content comes from data/site.ts and data/socials.ts.

# Colors
C_DEFAULT=$'\\033[0m'
C_WHITE=$'\\033[1;37m'
C_BLACK=$'\\033[30m'
C_RED=$'\\033[31m'
C_ORANGE=$'\\033[38;5;208m'
C_GREEN=$'\\033[32m'
C_YELLOW=$'\\033[33m'
C_BLUE=$'\\033[34m'
C_MAGENTA=$'\\033[35m'
C_CYAN=$'\\033[36m'
C_GRAY=$'\\033[90m'

# Styles
S_BOLD=$'\\033[1m'
S_UNDERLINE=$'\\033[4m'

# Icons with colors
I_WEBSITE=$'\\033[38;5;81m🌍'
I_EMAIL=$'\\033[38;5;208m📧'
I_GITHUB=$'\\033[38;5;245m🐙'
I_LINKEDIN=$'\\033[38;5;33m💼'

# Card Content
CARD_NAME=${sq(site.name)}
CARD_TITLE=${sq(site.title)}
CARD_WEBSITE=${sq(site.url)}
CARD_EMAIL=${sq(site.email)}
CARD_GITHUB=${sq(byIcon("github").href)}
CARD_LINKEDIN=${sq(byIcon("linkedin").href)}
CARD_REPO=${sq(site.repo)}
CARD_BIO_L1=${sq(site.bio[0])}
CARD_BIO_L2=${sq(site.bio[1])}
`;

const target = join(process.cwd(), "public/curl/config.sh");
writeFileSync(target, config);
console.log(`generated ${target}`);
